version: '3'
services:
  node1:
    build: 
      dockerfile: ./backend/app.dockerfile
      context: .
    image: ruhan/url-shortener-backend  
    container_name: url-shortener-backend-1
    links:
      - redis
    ports:
      - "5000"
    depends_on:
      - "redis"

  node2:
    build: 
      dockerfile: ./backend/app.dockerfile
      context: .
    image: ruhan/url-shortener-backend  
    container_name: url-shortener-backend-2
    links:
      - redis
    ports:
      - "5000"
    depends_on:
      - "redis"

  node3:
    build: 
      dockerfile: ./backend/app.dockerfile
      context: .
    image: ruhan/url-shortener-backend  
    container_name: url-shortener-backend-3
    links:
      - redis
    ports:
      - "5000"
    depends_on:
      - "redis"

  nginx:
    build:
      dockerfile: ./nginx/nginx.dockerfile
      context: .
    image: ruhan/nginx
    container_name: nginx
    ports: 
      - "80:80"
    depends_on:
      - "node1"
      - "node2"
      - "node3"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"